# Generated by Django 5.2.9 on 2026-01-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
        ('shop', '0003_commande_total'),
    ]

    operations = [
    ]
